export default {
  products: [
    {
      _id: '1',
      name: 'NIKE Mens Legend Short Sleeve Tee',
      category: 'Shirts',
      iamge: 'images/product-1.jpg',
      price: 50,
      barnd: 'Nike',
      raiting: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: '2',
      name: 'Nike Mens Running Shoes',
      category: 'Shoes',
      iamge: 'images/product-2.jpg',
      price: 60,
      barnd: 'Nike',
      raiting: 5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: '3',
      name: 'NIKE Mens Layup 2 Shorts',
      category: 'Shorts',
      iamge: 'images/product-3.jpg',
      price: 53,
      barnd: 'Nike',
      raiting: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: '4',
      name: 'NIKE Mens Legend Short Sleeve Tee',
      category: 'Shirts',
      iamge: 'images/product-4.jpg',
      price: 45,
      barnd: 'Nike',
      raiting: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: '5',
      name: 'Nike Mens Dri-Fit Therma Training Pants',
      category: 'Trousers',
      iamge: 'images/product-5.jpg',
      price: 55,
      barnd: 'Nike',
      raiting: 4,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: '6',
      name: 'Nike Mens Fitness Workout Track Jacket',
      category: 'Jacket',
      iamge: 'images/product-6.jpg',
      price: 90,
      barnd: 'Nike',
      raiting: 5,
      numReviews: 10,
      countInStock: 6,
    },
  ],
};
